### ISSUE TITLE
Isn't there a need for "update()" method for entities?

### ISSUE THREAD

**Issue by beremaran** [barisdoga2/Project-X#1]
Okay, entities rendered by `render()` method of the Renderer, but how will we update the logic of the entities? 

I see `move()` and `checkInputs()` methods of the `Player` class, but there is should be a way-more generic way to update entity logic.

**Comment by barisdoga2** [comment]
Solved by adding Update method to each entity class.

**Comment by barisdoga2** [comment]
Solved by adding Update method to each entity class.
Fixed#1
